package view;

import controller.AlunoDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;

public class AlunoForm extends javax.swing.JPanel {

    public AlunoForm() {
        initComponents();
        
        preencherTabela(new AlunoDAO().listar());
    }
    
    private void configurarTabela(){
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("Id");
        m.addColumn("Nome");
        m.addColumn("Email");
        m.addColumn("Telefone");
        m.addColumn("Data de Nascimento");
        tabAlunos.setModel(m);
    }
    
    private void preencherTabela(List<Aluno> lista){
        configurarTabela();
        DefaultTableModel m = (DefaultTableModel)tabAlunos.getModel();
        for(Aluno a : lista){
            m.addRow(new Object[]{a.getId(),a.getNome(),a.getEmail(),a.getTelefone(),a.getDataNascimento()});
        }
        tabAlunos.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPesquisarPor = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        cbxPesquisarPor = new javax.swing.JComboBox<>();
        lblAlunos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabAlunos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        lblPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPesquisarPor.setText("Pesquisar por");

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        cbxPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxPesquisarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome", "Email", "Telefone", "Data de Nascimento" }));

        lblAlunos.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblAlunos.setText("Alunos");

        tabAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabAlunos);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlunos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPesquisarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addGap(283, 283, 283))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionar, btnAlterar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAlunos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarPor)
                    .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnAlterar))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        
        String chave = txtPesquisar.getText();
        
        if (chave.isEmpty()) {
            preencherTabela(new AlunoDAO().listar());
        } else {
            String filtro = cbxPesquisarPor.getSelectedItem().toString();
            
            if (filtro.equals("Id")) {
                preencherTabela(new AlunoDAO().pesquisarPorId(chave));
            } else if (filtro.equals("Nome")) {
                preencherTabela(new AlunoDAO().pesquisarPorNome(chave));
            } else if (filtro.equals("Email")) {
                preencherTabela(new AlunoDAO().pesquisarPorEmail(chave));
            } else if (filtro.equals("Telefone")) {
                preencherTabela(new AlunoDAO().pesquisarPorTelefone(chave));
            } else if (filtro.equals("Data de Nascimento")) {
                preencherTabela(new AlunoDAO().pesquisarPorData(chave));
            }
        }
        
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        int linha = tabAlunos.getSelectedRow();
        
        if (linha >= 0) {
            int id = (int) tabAlunos.getValueAt(linha, 0);
            String nome = tabAlunos.getValueAt(linha, 1).toString();
            String email = tabAlunos.getValueAt(linha, 2).toString();
            String telefone = tabAlunos.getValueAt(linha, 3).toString();
            String dataNascimento = tabAlunos.getValueAt(linha, 4).toString();

            Aluno a = new Aluno(id, nome, email, telefone, dataNascimento);

            AlterarAluno alterar = new AlterarAluno(a);
            alterar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno na tabela para alterar.");
        }
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tabAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabAlunosMouseClicked
                
    }//GEN-LAST:event_tabAlunosMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        CadastroAlunos c = new CadastroAlunos();
        c.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JComboBox<String> cbxPesquisarPor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlunos;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JTable tabAlunos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
