/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ProfessorDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Professor;

/**
 *
 * @author Micro
 */
public class ProfessorForm extends javax.swing.JPanel {

    /**
     * Creates new form Professores
     */
    public ProfessorForm() {
        initComponents();
        preencherTabela(new ProfessorDAO().listar());
    }
    
    private void configurarTabela(){
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("id");
        m.addColumn("Nome");
        m.addColumn("Email");
        m.addColumn("Telefone");
        tabProfessores.setModel(m);
    }
    
    private void preencherTabela(List<Professor> lista){
        configurarTabela();
        DefaultTableModel m = (DefaultTableModel)tabProfessores.getModel();
        for(Professor p : lista){
            m.addRow(new Object[]{p.getId(),p.getNome(),p.getEmail(),p.getTelefone()});
        }
        tabProfessores.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProfessores = new javax.swing.JLabel();
        lblPesquisarPor = new javax.swing.JLabel();
        cbxPesquisarPor = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProfessores = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblProfessores.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblProfessores.setText("Professores");

        lblPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPesquisarPor.setText("Pesquisar por");

        cbxPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxPesquisarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome", "Email", "Telefone" }));

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        tabProfessores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabProfessores);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionar.setText("Adicionar");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Alterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfessores)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPesquisarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(283, 283, 283))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionar, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProfessores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarPor)
                    .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(jButton1))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        String chave = txtPesquisar.getText();

        if (chave.isEmpty()) {
            preencherTabela(new ProfessorDAO().listar());
        } else {
            String filtro = cbxPesquisarPor.getSelectedItem().toString();

            if (filtro.equals("Id")) {
                preencherTabela(new ProfessorDAO().pesquisarPorId(chave));
            } else if (filtro.equals("Nome")) {
                preencherTabela(new ProfessorDAO().pesquisarPorNome(chave));
            } else if (filtro.equals("Email")) {
                preencherTabela(new ProfessorDAO().pesquisarPorEmail(chave));
            } else if (filtro.equals("Telefone")) {
                preencherTabela(new ProfessorDAO().pesquisarPorTelefone(chave));
            }
        }

    }//GEN-LAST:event_txtPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JComboBox<String> cbxPesquisarPor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JLabel lblProfessores;
    private javax.swing.JTable tabProfessores;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
