package view;

import controller.TurmaDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Turma;

public class TurmaForm extends javax.swing.JPanel {

    /**
     * Creates new form Turma
     */
    public TurmaForm() {
        initComponents();
        preencherTabela(new TurmaDAO().listar());
    }
    
    private void configurarTabela(){
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("id");
        m.addColumn("Nome");
        m.addColumn("Curso");
        m.addColumn("Nível");
        m.addColumn("Professor");
        m.addColumn("Horário");
        tabTurmas.setModel(m);
    }
    
    private void preencherTabela(List<Turma> lista){
        configurarTabela();
        DefaultTableModel m = (DefaultTableModel)tabTurmas.getModel();
        for(Turma t : lista){
            
            m.addRow(new Object[]{t.getId(),t.getNome(),t.getCursoId(),t.getNivelId(),t.getProfessorId(),t.getHorario()});
        }
        tabTurmas.setModel(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTurmas = new javax.swing.JLabel();
        lblPesquisarPor = new javax.swing.JLabel();
        cbxPesquisarPor = new javax.swing.JComboBox<>();
        txtPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabTurmas = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lblTurmas.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblTurmas.setText("Turmas");

        lblPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPesquisarPor.setText("Pesquisar por");

        cbxPesquisarPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxPesquisarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Nome", "Curso", "Nível", "Professor", "Horário" }));

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        tabTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabTurmas);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionar.setText("Adicionar");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Alterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTurmas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPesquisarPor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 323, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(283, 283, 283))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionar, jButton1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTurmas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisarPor)
                    .addComponent(cbxPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(jButton1))
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        String chave = txtPesquisar.getText();

        if (chave.isEmpty()) {
            preencherTabela(new TurmaDAO().listar());
        } else {
            String filtro = cbxPesquisarPor.getSelectedItem().toString();

            if (filtro.equals("Id")) {
                preencherTabela(new TurmaDAO().pesquisarPorId(chave));
            } else if (filtro.equals("Nome")) {
                preencherTabela(new TurmaDAO().pesquisarPorNome(chave));
            } else if (filtro.equals("Curso")) {
                preencherTabela(new TurmaDAO().pesquisarPorCursoId(chave));
            } else if (filtro.equals("Nível")) {
                preencherTabela(new TurmaDAO().pesquisarPorNivelId(chave));
            } else if (filtro.equals("Professor")) {
                preencherTabela(new TurmaDAO().pesquisarPorProfessorId(chave));
            } else if (filtro.equals("Horário")) {
                preencherTabela(new TurmaDAO().pesquisarPorHorario(chave));
            }
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JComboBox<String> cbxPesquisarPor;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPesquisarPor;
    private javax.swing.JLabel lblTurmas;
    private javax.swing.JTable tabTurmas;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
